markdown: rdiscount

auto: true

pygments: true

paginate: 5

production: false

future: false

source: /Users/extracbd/Desktop/workspace-fullservice-duinos/arduino-minas.github.com/
destination: /Users/extracbd/htdocs/arduino-minas

lsi: true

permalink: /:year-:month-:day-:title.html

title: Arduino Minas

description: Página dos projetos hospedados no GitHub, criados e desenvolvidos no Arduino Minas
url: http://arduinominas.com.br/
author: Carlos Delfino (@CarlosDelfino), Fernando Passe (@fernandopasse)
  
exclude: [Rakefile, rakefile, makefile, README.md, LICENSE, 'README.markdown', 'README_FOR_COLLABORATORS.markdown', 'Gemfile.lock', 'Gemfile']
