# Site
name: Arduino Minas
description: Cursos Arduino Minas, do Arduino ao Universo de Tecnologias para o sucesso de seu projeto!
meta_description: "Um lugar para construir seu projeto e desenvolver novas ideias!"
paginate: 12
email: 'consultoria@carlosdelfinfo.eti.br'
disqus: 'carlosdelfino'
sharethis: 
  show: true;
  property: 5b326ee13e2f6e001148ddca
  product: 'sticky-share-buttons'
google_analytics: "UA-21710445-1"

locale: "pt_BR"
lang: "pt_BR"
charset: "utf-8"
encoding: "utf-8" 

baseurl: ""

images:
  baseurl: 'assets/images'
  logo: 'logo.png'
  favicon: 'favicon.png'

author: delfino

github: 
  org: ArduinoMinas
facebook:
  fanpage: cursoarduinominas

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/:name/'
    tag: '/tag/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

# MailChip
mailchimp:
  show: false

## ads
ads:
  show: true

exclude: 
  - /assets/images/logo.xcf,
  - /assets/images/react_redux.xcf]