safe: true

markdown: rdiscount

pygments: true

paginate: 5

future: false

future: false

lsi: true

permalink: /:categories/:year-:month-:day-:title.html

title: Arduino Minas
slogan: Tecnologia, Criatividade e Conhecimento Compartilhado
defaultlogo: /images/logo/logo-318x330x72.png

description: Página dos projetos hospedados no GitHub, criados e desenvolvidos no Arduino Minas
url: http://arduinominas.com.br
uri: arduinominas.com.br

logo: /images/logo/logo-318x330x72.png

fbappid: 189875687827636
fbadmins: carlosdelfinocarvalhopinheiro

author: Carlos Delfino (@CarlosDelfino), Fernando Passe (@fernandopasse)
  
